{"uid":"16a4c18dad2b0d1a","name":"test_scenario_3_addresses","fullName":"tests.tests_steps.TestScenario3addresses#test_scenario_3_addresses","historyId":"0c7f0b05284a713e540e7fc956db332e","time":{"start":1659522407652,"stop":1659522409652,"duration":2000},"status":"failed","statusMessage":"AssertionError","statusTrace":"self = <tests_steps.TestScenario3addresses object at 0x7f521c46ef50>\n\n    def test_scenario_3_addresses(self):\n        test_scenario_3 = Scenario_Three()\n>       test_scenario_3.go_to_your_addresses()\n\ntests/tests_steps.py:42: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.Scenario3.Scenario_Three object at 0x7f521c33d300>\n\n    @allure.step(\"Go to Your Addresses\")\n    def go_to_your_addresses(self):\n        self.visit(self.base_url)\n        self.targeting(*self.locator_dictionary['buttonGoToSignIn'])\n        self.find_element(*self.locator_dictionary['buttonYourAddresses']).click()\n>       assert 1 == 2\nE       AssertionError\n\npages/Scenario3.py:26: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"start_session","time":{"start":1659522404591,"stop":1659522407651,"duration":3060},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"testStage":{"status":"failed","statusMessage":"AssertionError","statusTrace":"self = <tests_steps.TestScenario3addresses object at 0x7f521c46ef50>\n\n    def test_scenario_3_addresses(self):\n        test_scenario_3 = Scenario_Three()\n>       test_scenario_3.go_to_your_addresses()\n\ntests/tests_steps.py:42: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.Scenario3.Scenario_Three object at 0x7f521c33d300>\n\n    @allure.step(\"Go to Your Addresses\")\n    def go_to_your_addresses(self):\n        self.visit(self.base_url)\n        self.targeting(*self.locator_dictionary['buttonGoToSignIn'])\n        self.find_element(*self.locator_dictionary['buttonYourAddresses']).click()\n>       assert 1 == 2\nE       AssertionError\n\npages/Scenario3.py:26: AssertionError","steps":[{"name":"Go to Your Addresses","time":{"start":1659522407652,"stop":1659522409651,"duration":1999},"status":"failed","statusMessage":"AssertionError\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/autotetsamazon/autotetsamazon/pages/Scenario3.py\", line 26, in go_to_your_addresses\n    assert 1 == 2\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true}],"attachments":[{"uid":"1300973b69e5fef0","name":"Current URL","source":"1300973b69e5fef0.uri","type":"text/uri-list","size":22},{"uid":"601af0e1a37eda12","name":"Screenshot","source":"601af0e1a37eda12.png","type":"image/png","size":33935}],"parameters":[],"stepsCount":1,"attachmentsCount":2,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[{"name":"start_session::0","time":{"start":1659522409799,"stop":1659522409860,"duration":61},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('start_session')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"tests_steps"},{"name":"subSuite","value":"TestScenario3addresses"},{"name":"host","value":"fv-az119-838"},{"name":"thread","value":"2252-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.tests_steps"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":4,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":6},"items":[{"uid":"ba0a59006e462456","reportUrl":"https://Spirlhark.github.io/autotetsamazon/4//#testresult/ba0a59006e462456","status":"failed","statusDetails":"AssertionError","time":{"start":1659511883277,"stop":1659511885081,"duration":1804}},{"uid":"ec402f164dcb8902","reportUrl":"https://Spirlhark.github.io/autotetsamazon/3//#testresult/ec402f164dcb8902","status":"failed","statusDetails":"AssertionError","time":{"start":1659468876221,"stop":1659468879162,"duration":2941}},{"uid":"ba4e6ee11e7fd445","reportUrl":"https://Spirlhark.github.io/autotetsamazon/3//#testresult/ba4e6ee11e7fd445","status":"failed","statusDetails":"AssertionError","time":{"start":1659460432862,"stop":1659460434855,"duration":1993}},{"uid":"26c82983c6b9d1f1","reportUrl":"https://Spirlhark.github.io/autotetsamazon/2//#testresult/26c82983c6b9d1f1","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55d8d0986cd3 <unknown>\n#1 0x55d8d078e968 <unknown>\n#2 0x55d8d07b325c <unknown>\n#3 0x55d8d07ae8fa <unknown>\n#4 0x55d8d07e994a <unknown>\n#5 0x55d8d07e3aa3 <unknown>\n#6 0x55d8d07b93fa <unknown>\n#7 0x55d8d07ba555 <unknown>\n#8 0x55d8d09ce2bd <unknown>\n#9 0x55d8d09d2418 <unknown>\n#10 0x55d8d09b836e <unknown>\n#11 0x55d8d09d3078 <unknown>\n#12 0x55d8d09acbb0 <unknown>\n#13 0x55d8d09efd58 <unknown>\n#14 0x55d8d09efed8 <unknown>\n#15 0x55d8d0a09cfd <unknown>\n#16 0x7f0112c40609 <unknown>","time":{"start":1659439731594,"stop":1659439731594,"duration":0}},{"uid":"b93a34f4618c9eaf","reportUrl":"https://Spirlhark.github.io/autotetsamazon/1//#testresult/b93a34f4618c9eaf","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55a241c45cd3 <unknown>\n#1 0x55a241a4d968 <unknown>\n#2 0x55a241a7225c <unknown>\n#3 0x55a241a6d8fa <unknown>\n#4 0x55a241aa894a <unknown>\n#5 0x55a241aa2aa3 <unknown>\n#6 0x55a241a783fa <unknown>\n#7 0x55a241a79555 <unknown>\n#8 0x55a241c8d2bd <unknown>\n#9 0x55a241c91418 <unknown>\n#10 0x55a241c7736e <unknown>\n#11 0x55a241c92078 <unknown>\n#12 0x55a241c6bbb0 <unknown>\n#13 0x55a241caed58 <unknown>\n#14 0x55a241caeed8 <unknown>\n#15 0x55a241cc8cfd <unknown>\n#16 0x7f2d293e9609 <unknown>","time":{"start":1659438875585,"stop":1659438875585,"duration":0}}]},"tags":["@pytest.mark.usefixtures('start_session')"]},"source":"16a4c18dad2b0d1a.json","parameterValues":[]}